######################################################################
# Automatically generated by qmake (3.0) ? 6 23 07:58:05 2019
######################################################################

TEMPLATE = app
TARGET = PCMsgSocket
INCLUDEPATH += .

# Input
HEADERS += Consts.h PCMsgSocket.h GeneratedFiles/ui_PCMsgSocket.h
FORMS += PCMsgSocket.ui
SOURCES += main.cpp PCMsgSocket.cpp GeneratedFiles/qrc_PCMsgSocket.cpp
RESOURCES += PCMsgSocket.qrc
